---
- name: Download the Go tarball
  get_url:
    url: "https://dl.google.com/go/{{ go_tarball }}"
    dest: /usr/local/src/{{ go_tarball }}
    checksum: "{{ go_tarball_checksum }}"

- name: Extract the Go tarball
  unarchive:
    src: /usr/local/src/{{ go_tarball }}
    dest: /usr/local
    copy: no

- name: Set environment variables
  copy:
    src: golang.sh
    dest: /etc/profile.d
