---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - apt: "name={{ item }} state=present"
      with_items:
        - git
        - wget
        - curl
        - vim
        - ubuntu-desktop
