---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - apt: "name={{ item }} state=present"
      with_items:
        - git
        - wget
        - curl
        - vim
        - ubuntu-desktop
    - import_role:
        name: golang # Based on https://github.com/jlund/ansible-go
    - import_role:
        name: vscode # Based on https://github.com/gantsign/ansible-role-visual-studio-code
